version: '3.9'

services:
  web:
    build: .
    command:  gunicorn application.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/stock/
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    networks:
      - postgres
      - django
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - 1221:80
    networks:
      - django
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

  postgres:
    container_name: postgres_stock
    image: postgres
    environment:
      POSTGRES_USER: dpudovkin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5436:5432"
    networks:
      - postgres
    restart: unless-stopped

  redis-server:
    container_name: celery_redis
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6383:6379"

networks:
  postgres:
    driver: bridge
  django:
    driver: bridge

volumes:
    postgres:
    static_volume: