version: '3.9'

services:
  postgres:
    container_name: postgres_stock
    image: postgres
    environment:
      POSTGRES_USER: dpudovkin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped

  redis-server:
    container_name: celery_redis
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6382:6379"

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
#    environment:
#      - http.host=0.0.0.0
#      - transport.host=127.0.0.1
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xmx1024m -Xms1024m"
#    deploy:
#      resources:
#        limits:
#          cpus: 0.50
#          memory: 2048M
#        reservations:
#          cpus: 0.25
#          memory: 2040M
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    ports:
#      - "9201:9200"
#      - "9301:9300"
#    networks:
#      - docker_elk
#  kibana:
#    image: kibana:7.14.2
#    ports:
#      - "5602:5601"
#    links:
#      - elasticsearch
#    networks:
#      - docker_elk

networks:
  postgres:
    driver: bridge
#  docker_elk:
#    driver: bridge

volumes:
    postgres:
    pgadmin: