# Generated by Django 3.2.9 on 2021-11-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30, verbose_name='Должность сотрудника')),
                ('status', models.CharField(max_length=30, verbose_name='Статус сотрудника')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='Пользователь')),
            ],
        ),
    ]
