# Generated by Django 3.2.9 on 2021-11-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Наименование адреса')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Ширина')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость заказа для клиента')),
                ('comment', models.CharField(default='', max_length=255, verbose_name='Дополнительный комментарий к заказу')),
                ('status', models.CharField(default='NEW', max_length=20, verbose_name='Статус заказа')),
                ('base_award', models.IntegerField(default=0, verbose_name='Базовое вознаграждение курьеру за выполненный заказ')),
                ('arriving_address_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_orders', to='orders.address', verbose_name='Адрес отправления заказа')),
                ('arriving_client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_orders', to='clients.client', verbose_name='Клиент отдающий отправление')),
                ('destination_address_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_orders', to='orders.address', verbose_name='Адрес назначения заказа')),
                ('destination_client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_orders', to='clients.client', verbose_name='Клиент получающий отправление')),
                ('performer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Курьер')),
            ],
        ),
    ]
