version: '3.9'

services:
  postgres:
    container_name: postgres_stock
    image: postgres
    environment:
      POSTGRES_USER: dpudovkin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped

  redis-server:
    container_name: celery_redis
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6382:6379"

  centrifugal:
    container_name: centrifugo
    image: centrifugo/centrifugo
    command: centrifugo -c config.json --port=8086
    ports:
    - "8086:8086"
    volumes:
    - "./centrifugo:/centrifugo"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536

networks:
  postgres:
    driver: bridge
  crv_network:
    driver: bridge

volumes:
    postgres:
    pgadmin: