# Generated by Django 3.2.9 on 2021-11-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='arriving_address_id',
            new_name='arriving_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='arriving_client_id',
            new_name='arriving_client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='destination_address_id',
            new_name='destination_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='destination_client_id',
            new_name='destination_client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='performer_id',
            new_name='performer',
        ),
    ]
