# Generated by Django 3.2.9 on 2021-11-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0005_auto_20211115_1257'),
        ('employees', '0003_rename_user_id_employee_user'),
        ('orders', '0002_auto_20211113_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arriving_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_orders',
                                    to='orders.address', verbose_name='Адрес отправления заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='arriving_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_orders',
                                    to='clients.client', verbose_name='Клиент отдающий отправление'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='received_orders', to='orders.address',
                                    verbose_name='Адрес назначения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='received_orders', to='clients.client',
                                    verbose_name='Клиент получающий отправление'),
        ),
        migrations.AlterField(
            model_name='order',
            name='performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee',
                                    verbose_name='Курьер'),
        ),
    ]
