# Generated by Django 3.2.9 on 2021-11-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='NOT VERIFIED', max_length=20, verbose_name='Статус клиента')),
            ],
        ),
    ]
