# Generated by Django 3.2.9 on 2021-11-13 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0002_employee_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='user',
        ),
    ]
