# Generated by Django 3.2.9 on 2021-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='displayed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='description', max_length=2500, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_country',
            field=models.CharField(default='description', max_length=128, null=True, verbose_name='Страна происхождения'),
        ),
    ]
