# Generated by Django 3.2.9 on 2021-11-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='NOT VERIFIED', max_length=20, verbose_name='Статус клиента')),
                ('home_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.address', verbose_name='Домашний адрес')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='Пользователь')),
            ],
        ),
    ]
